spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME:timemanager}
    username: ${DB_USER:timemanager}
    password: ${DB_PASSWORD:timemanager}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
